### PR TITLE
Show Load avg at sidebar

### PR DESCRIPTION
**Pull request by Moorviper**
added load avg

### CODE REVIEW

**Comment by plumpudding** [comment]
Do you have an example installation where I can take a look at it?

**Comment by plumpudding** [comment]
How do you determine the 'maximum' load (the load value at the very right)?

**Comment by plumpudding** [comment]
Suggestion:
Lock the scale to 0 (left) - 1 (very right)
Everything above 0.75 is colored yellow-ish
Everything above 1 is a red, full bar

**Comment by Moorviper** [comment]
ok i fix it



http://dev.meshviewer.net/

**Comment by plumpudding** [comment]
Should I see a difference?

**Comment by plumpudding** [comment]
O.o now you did more stuff in this branch. The problems are still remaining too.

**Comment by Moorviper** [comment]
i think i stash the changes go a little back merge your changes and apply and fix it :D

**Pull request closed without merging**
