### PR TITLE
Translate GW Mac to Names via Siteconf

### PR DESCRIPTION
**Pull request by PowerPan**

### CODE REVIEW

**Comment by plumpudding** [comment]
Thanks for the work, I have different plans. I want to read the names from the nodes data provided via the aliases.json.

On June 5, 2016 4:28:31 PM GMT+02:00, Johannes Rudolph <notifications@github.com> wrote:
>
>You can view, comment on, or merge this pull request online at:
>
>  https://github.com/plumpudding/hopglass/pull/42
>
>-- Commit Summary --
>
>  * extend gitignore
>  * add GW Translation from site.conf
>  * add example gw translation
>
>-- File Changes --
>
>    M .gitignore (1)
>    M config.json.example (7)
>    M lib/proportions.js (9)
>
>-- Patch Links --
>
>https://github.com/plumpudding/hopglass/pull/42.patch
>https://github.com/plumpudding/hopglass/pull/42.diff
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/plumpudding/hopglass/pull/42

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by PowerPan** [comment]
Hey

This is a second way to translate the names of an gateway and not a must have ;)

If somebody want to choose this way over the config.json he can do this, and of course over the way with the alias.json is possible as well.

**Comment by plumpudding** [comment]
I will accept this as a quick-and-dirty patch, but soon the existing data from aliases.json should be used.

**Comment by PowerPan** [comment]
At our Community it is not working with the aliases.json File

**Comment by plumpudding** [comment]
I said "soon". It isn't implemented.

**Comment by mar-v-in** [comment]
@plumpudding Are you already working on this? I guess I will find some time this weekend to work on it.

**Comment by plumpudding** [comment]
No, I haven't started working on this. I would like it to be done (at least partly) on the server-side though. It should work like this:
On the server-side in the hopglass provider the gateway is looked up in the macTable and is replaced with the resulting nodeid. If the lookup is unsuccessful, the mac is used.
On the client side the nodeid is looked up in the nodes object and the hostname of that node (the gateway) is used. As a fallback the given nodeid / mac is used.

**Comment by plumpudding** [comment]
Discussion can continue in https://github.com/hopglass/hopglass-server/issues/56

**Pull request closed without merging**
