### PR TITLE
Fix number of decimal places being displayed in the CPU load bar

### LINKED ISSUE #48: system load display issue
"0.14000000000000004"

Load only has two fractional digits, where does is imprecision come from?

http://i.imgur.com/DL6w4Ar.png

### PR DESCRIPTION
**Pull request by codedust**
Closes  #48

### CODE REVIEW

**Comment by xf-** [comment]
JS supports number..toFixed(2) - no Math needed

**Comment by codedust** [comment]
`toFixed` doesn't implement mathematical rounding.

https://stackoverflow.com/questions/11832914/round-to-at-most-2-decimal-places-in-javascript

**Comment by xf-** [comment]
In the most times a lot of 0 it is 0.120000002 and second decimal 0.005 "wrong" is not an issue for me. You will have the behavior of a float.

Examples:
1.000001 => 1
0.255 => 0.26
0.200000005 => 0.2
0.3 => 0.3

The advantage of toFixed(2) it it ensures always 2 decimals.

Examples:
1.000001 => 1.00
0.255 => 0.25
0.200000005 => 0.20
0.3 => 0.30

I looked at https://map.darmstadt.freifunk.net/data/nodes.json. maybe 15 numbers have more than 2 decimals and most have 0.1400000x. Only 2 have  0.2899999 and it would be "wrong". A lot of numbers have only 1 decimal.

**Comment by plumpudding** [comment]
@xf- it's not even a performance issue: https://jsperf.com/round-numbers-to-2-digits

**Pull request merged**
