### PR TITLE
patch: allow hiding of statistic elements and add cients/gw statistics

### PR DESCRIPTION
**Pull request by viisauksena**

### CODE REVIEW

**Comment by plumpudding** [comment]
Very nice code! One thing: Can you change the names from `gwTable` and `gw2Table` to gwNodesTable and gwClientsTable

**Comment by viisauksena** [comment]
nice idea .. hope that is fine now ... i havent checked it in real live yet (so better have an extra eye on it)

**Comment by plumpudding** [comment]
1) I will test it
2) you can do a `git rebase -i` and squash the commits into one. 
3) you should choose a commit message with the layout `module: change` so I suggest `proportions: allow hiding of statistics and add gateway client statistics`

**Comment by plumpudding** [comment]
Please change "Clients on Gateway" to something bilingual or German.

**Comment by viisauksena** [comment]
the arrow thing won't come,
the naming .. mhm .. i dont know - project is at the moment pretty far away for me, so i prefer to leave it as it is

**Comment by plumpudding** [comment]
Then I will have to change it. Half German half English is a no-go!

**Comment by viisauksena** [comment]
thx for good project and work

**Pull request merged**
